# Generated by Django 4.2.6 on 2023-11-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('entry', models.TextField(max_length=250)),
            ],
        ),
    ]
